name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

queue:
  name: TimeWarpEnterprises

variables:
 Major: '0'
 Minor: '1'
 Patch: '0'
 Version: "$(Major).$(Minor).$(Patch)-beta-$(Build.BuildID)"

steps:
- script: echo Version $(Version)
- script: echo BuildNumber $(Build.BuildNumber)
- script: echo BuildID $(Build.BuildID)
- script: echo Major $(Major)
- script: echo Minor $(Minor)
- script: echo Patch $(Patch)

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: source/BlazorState.Js

- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.1.302
  inputs:
    version: 2.1.302
  enabled: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config
  enabled: false

- task: DotNetCoreCLI@2
  displayName: Build all except the template project
  inputs:
    command: build
    projects: |
     **/*.csproj
     !**\TimeWarp.AspNetCore.Blazor.Templates.csproj
    arguments: --configuration debug    

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**\*Tests\*.csproj'
    arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  displayName: dotnet pack blazor-state
  inputs:
    command: pack
    packagesToPack: 'source\BlazorState\BlazorState.csproj'
    versionEnvVar: Version
    versioningScheme: byEnvVar
    # majorVersion: '$(Major)'
    # minorVersion: '$(Minor)'
    # patchVersion: '$(Patch)'
    configurationToPack: release
  enabled: true

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: custom
    custom: pack 
    arguments: >
      $(Build.SourcesDirectory)/source/BlazorState/BlazorState.csproj 
      --output $(Build.StagingDirectory) 
      /p:Configuration=release 
      --version-suffix beta-$(Build.BuildID) 
      --verbosity Detailed
  enabled: false

- task: NuGetCommand@2
  displayName: 'NuGet pack Templates'
  inputs:
    command: pack
    packagesToPack: $(Build.SourcesDirectory)/source/TimeWarp.AspNetCore.Blazor.Templates/TimeWarp.AspNetCore.Blazor.Templates.nuspec
    configurationToPack: debug
    versioningScheme: byEnvVar
    versionEnvVar: Version
    # majorVersion: '$(Major)'
    # minorVersion: '$(Minor)'
    # patchVersion: '$(Patch)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
    publishLocation: Container

- task: DotNetCoreCLI@2
  displayName: Push Nuget to MyGet
  inputs:
    command: custom
    custom: nuget
    arguments: 'push $(Build.ArtifactStagingDirectory)\*.nupkg -s https://www.myget.org/F/timewarp-enterprises/api/v3/index.json -k $(MyGetApiKey)'
