name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
 branches:
  include:
  - dev

queue:
  name: TimeWarpEnterprises

variables:
 Major: '0'
 Minor: '2'
 Patch: '1'
 Version: "$(Major).$(Minor).$(Patch)-beta-$(Build.BuildID)"

steps:
- script: echo Version $(Version)

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: source/BlazorState.Js

- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.1.403
  inputs:
    version: 2.1.403

- task: DotNetCoreCLI@2
  displayName: Build all
  inputs:
    command: build
    projects: '**/*.csproj'
    configuration: debug     

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**\*Tests\*.csproj'
    configurationToPack: debug

- task: DotNetCoreCLI@2
  displayName: dotnet pack blazor-state
  inputs:
    command: pack
    packagesToPack: 'source\BlazorState\BlazorState.csproj'
    versionEnvVar: Version
    versioningScheme: byEnvVar
    configurationToPack: debug

- task: NuGetCommand@2
  displayName: 'NuGet pack Templates'
  inputs:
    command: pack
    packagesToPack: $(Build.SourcesDirectory)/source/TimeWarp.AspNetCore.Blazor.Templates/TimeWarp.AspNetCore.Blazor.Templates.nuspec
    configurationToPack: debug
    versioningScheme: byEnvVar
    versionEnvVar: Version

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
    publishLocation: Container

- task: DotNetCoreCLI@2
  displayName: Push Nuget to MyGet
  inputs:
    command: custom
    custom: nuget
    arguments: 'push $(Build.ArtifactStagingDirectory)\*.nupkg -s https://www.myget.org/F/timewarp-enterprises/api/v3/index.json -k $(MyGetApiKey)'
